version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: "no"
    command:
      - start
      - --log=trace
      - --user=${SURREAL_USERNAME:-root} #default user
      - --pass=${SURREAL_PASSWORD:-root} #default password
    ports:
      - 127.0.0.1:${SURREAL_PORT:-8000}:8000